// Code generated by goyacc -p expr -o pkg/logql/expr.y.go pkg/logql/expr.y. DO NOT EDIT.

package logql

import __yyfmt__ "fmt"


import (
	"github.com/grafana/loki/pkg/logql/log"
	"github.com/prometheus/prometheus/pkg/labels"
	"time"
)

type exprSymType struct {
	yys                   int
	Expr                  Expr
	Filter                labels.MatchType
	Grouping              *grouping
	Labels                []string
	LogExpr               LogSelectorExpr
	LogRangeExpr          *logRange
	Matcher               *labels.Matcher
	Matchers              []*labels.Matcher
	RangeAggregationExpr  SampleExpr
	RangeOp               string
	ConvOp                string
	Selector              []*labels.Matcher
	VectorAggregationExpr SampleExpr
	MetricExpr            SampleExpr
	VectorOp              string
	FilterOp              string
	BinOpExpr             SampleExpr
	LabelReplaceExpr      SampleExpr
	binOp                 string
	bytes                 uint64
	str                   string
	duration              time.Duration
	LiteralExpr           *literalExpr
	BinOpModifier         BinOpOptions
	LabelParser           *labelParserExpr
	LineFilters           *lineFilterExpr
	LineFilter            *lineFilterExpr
	PipelineExpr          MultiStageExpr
	PipelineStage         StageExpr
	BytesFilter           log.LabelFilterer
	NumberFilter          log.LabelFilterer
	DurationFilter        log.LabelFilterer
	LabelFilter           log.LabelFilterer
	UnitFilter            log.LabelFilterer
	LineFormatExpr        *lineFmtExpr
	LabelFormatExpr       *labelFmtExpr
	LabelFormat           log.LabelFmt
	LabelsFormat          []log.LabelFmt
	JSONExpressionParser  *jsonExpressionParser
	JSONExpression        log.JSONExpression
	JSONExpressionList    []log.JSONExpression
	UnwrapExpr            *unwrapExpr
	OffsetExpr            *offsetExpr
}

const BYTES = 57346
const IDENTIFIER = 57347
const STRING = 57348
const NUMBER = 57349
const DURATION = 57350
const RANGE = 57351
const MATCHERS = 57352
const LABELS = 57353
const EQ = 57354
const RE = 57355
const NRE = 57356
const OPEN_BRACE = 57357
const CLOSE_BRACE = 57358
const OPEN_BRACKET = 57359
const CLOSE_BRACKET = 57360
const COMMA = 57361
const DOT = 57362
const PIPE_MATCH = 57363
const PIPE_EXACT = 57364
const OPEN_PARENTHESIS = 57365
const CLOSE_PARENTHESIS = 57366
const BY = 57367
const WITHOUT = 57368
const COUNT_OVER_TIME = 57369
const RATE = 57370
const SUM = 57371
const AVG = 57372
const MAX = 57373
const MIN = 57374
const COUNT = 57375
const STDDEV = 57376
const STDVAR = 57377
const BOTTOMK = 57378
const TOPK = 57379
const BYTES_OVER_TIME = 57380
const BYTES_RATE = 57381
const BOOL = 57382
const JSON = 57383
const REGEXP = 57384
const LOGFMT = 57385
const PIPE = 57386
const LINE_FMT = 57387
const LABEL_FMT = 57388
const UNWRAP = 57389
const AVG_OVER_TIME = 57390
const SUM_OVER_TIME = 57391
const MIN_OVER_TIME = 57392
const MAX_OVER_TIME = 57393
const STDVAR_OVER_TIME = 57394
const STDDEV_OVER_TIME = 57395
const QUANTILE_OVER_TIME = 57396
const BYTES_CONV = 57397
const DURATION_CONV = 57398
const DURATION_SECONDS_CONV = 57399
const FIRST_OVER_TIME = 57400
const LAST_OVER_TIME = 57401
const ABSENT_OVER_TIME = 57402
const LABEL_REPLACE = 57403
const UNPACK = 57404
const OFFSET = 57405
const IP = 57406
const OR = 57407
const AND = 57408
const UNLESS = 57409
const CMP_EQ = 57410
const NEQ = 57411
const LT = 57412
const LTE = 57413
const GT = 57414
const GTE = 57415
const ADD = 57416
const SUB = 57417
const MUL = 57418
const DIV = 57419
const MOD = 57420
const POW = 57421

var exprToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"BYTES",
	"IDENTIFIER",
	"STRING",
	"NUMBER",
	"DURATION",
	"RANGE",
	"MATCHERS",
	"LABELS",
	"EQ",
	"RE",
	"NRE",
	"OPEN_BRACE",
	"CLOSE_BRACE",
	"OPEN_BRACKET",
	"CLOSE_BRACKET",
	"COMMA",
	"DOT",
	"PIPE_MATCH",
	"PIPE_EXACT",
	"OPEN_PARENTHESIS",
	"CLOSE_PARENTHESIS",
	"BY",
	"WITHOUT",
	"COUNT_OVER_TIME",
	"RATE",
	"SUM",
	"AVG",
	"MAX",
	"MIN",
	"COUNT",
	"STDDEV",
	"STDVAR",
	"BOTTOMK",
	"TOPK",
	"BYTES_OVER_TIME",
	"BYTES_RATE",
	"BOOL",
	"JSON",
	"REGEXP",
	"LOGFMT",
	"PIPE",
	"LINE_FMT",
	"LABEL_FMT",
	"UNWRAP",
	"AVG_OVER_TIME",
	"SUM_OVER_TIME",
	"MIN_OVER_TIME",
	"MAX_OVER_TIME",
	"STDVAR_OVER_TIME",
	"STDDEV_OVER_TIME",
	"QUANTILE_OVER_TIME",
	"BYTES_CONV",
	"DURATION_CONV",
	"DURATION_SECONDS_CONV",
	"FIRST_OVER_TIME",
	"LAST_OVER_TIME",
	"ABSENT_OVER_TIME",
	"LABEL_REPLACE",
	"UNPACK",
	"OFFSET",
	"IP",
	"OR",
	"AND",
	"UNLESS",
	"CMP_EQ",
	"NEQ",
	"LT",
	"LTE",
	"GT",
	"GTE",
	"ADD",
	"SUB",
	"MUL",
	"DIV",
	"MOD",
	"POW",
}
var exprStatenames = [...]string{}

const exprEofCode = 1
const exprErrCode = 2
const exprInitialStackSize = 16


var exprExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
}

const exprPrivate = 57344

const exprLast = 490

var exprAct = [...]int{

	233, 186, 76, 4, 167, 58, 156, 5, 161, 195,
	67, 109, 50, 57, 118, 131, 69, 2, 45, 46,
	47, 48, 49, 50, 72, 42, 43, 44, 51, 52,
	55, 56, 53, 54, 45, 46, 47, 48, 49, 50,
	43, 44, 51, 52, 55, 56, 53, 54, 45, 46,
	47, 48, 49, 50, 47, 48, 49, 50, 127, 129,
	130, 65, 236, 98, 169, 129, 130, 102, 63, 64,
	241, 61, 120, 238, 289, 83, 77, 78, 270, 135,
	307, 289, 133, 269, 302, 140, 51, 52, 55, 56,
	53, 54, 45, 46, 47, 48, 49, 50, 292, 141,
	236, 142, 143, 144, 145, 146, 147, 148, 149, 150,
	151, 152, 153, 154, 155, 128, 66, 237, 238, 164,
	175, 170, 173, 174, 171, 172, 182, 65, 272, 273,
	274, 99, 276, 294, 63, 64, 269, 177, 237, 250,
	250, 193, 189, 197, 252, 251, 239, 187, 261, 198,
	190, 65, 238, 182, 279, 185, 182, 188, 63, 64,
	65, 277, 199, 260, 201, 202, 203, 63, 64, 197,
	242, 238, 239, 238, 248, 245, 236, 65, 183, 115,
	191, 188, 66, 122, 63, 64, 231, 234, 196, 240,
	188, 243, 133, 98, 246, 102, 247, 112, 286, 235,
	232, 65, 115, 244, 115, 121, 66, 188, 63, 64,
	305, 115, 256, 254, 185, 66, 158, 176, 158, 65,
	112, 206, 112, 139, 138, 158, 63, 64, 132, 112,
	137, 188, 66, 81, 115, 262, 12, 264, 266, 74,
	268, 98, 301, 115, 134, 267, 278, 263, 158, 188,
	98, 12, 112, 280, 282, 75, 66, 77, 78, 134,
	249, 112, 159, 157, 283, 284, 207, 204, 200, 98,
	285, 159, 157, 192, 66, 184, 287, 288, 126, 105,
	107, 106, 293, 113, 114, 241, 15, 208, 265, 297,
	65, 298, 299, 205, 12, 157, 300, 63, 64, 291,
	108, 303, 6, 290, 275, 124, 19, 20, 33, 34,
	36, 37, 35, 38, 39, 40, 41, 21, 22, 123,
	60, 213, 125, 179, 214, 212, 80, 23, 24, 25,
	26, 27, 28, 29, 115, 194, 306, 30, 31, 32,
	18, 258, 259, 12, 210, 66, 178, 211, 209, 79,
	304, 6, 112, 16, 17, 19, 20, 33, 34, 36,
	37, 35, 38, 39, 40, 41, 21, 22, 295, 255,
	105, 107, 106, 253, 113, 114, 23, 24, 25, 26,
	27, 28, 29, 296, 136, 230, 30, 31, 32, 18,
	228, 108, 12, 229, 227, 225, 181, 281, 226, 224,
	6, 180, 16, 17, 19, 20, 33, 34, 36, 37,
	35, 38, 39, 40, 41, 21, 22, 82, 222, 179,
	219, 223, 221, 220, 218, 23, 24, 25, 26, 27,
	28, 29, 178, 3, 165, 30, 31, 32, 18, 216,
	68, 257, 217, 215, 168, 71, 163, 162, 73, 73,
	168, 16, 17, 110, 160, 101, 166, 104, 103, 59,
	116, 84, 85, 86, 87, 88, 89, 90, 91, 92,
	93, 94, 95, 96, 97, 111, 117, 100, 11, 10,
	9, 119, 14, 8, 271, 13, 7, 70, 62, 1,
}
var exprPact = [...]int{

	279, -1000, -40, -1000, -1000, 276, 279, -1000, -1000, -1000,
	-1000, -1000, 443, 216, 232, -1000, 342, 319, 210, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, 35, 35, 35, 35, 35, 35, 35, 35,
	35, 35, 35, 35, 35, 35, 35, 276, -1000, 47,
	329, -1000, 8, -1000, -1000, -1000, -1000, 181, 159, -40,
	303, 262, -1000, 46, 221, 377, 207, 201, 200, -1000,
	-1000, 279, 279, -1000, 279, 279, 279, 279, 279, 279,
	279, 279, 279, 279, 279, 279, 279, 279, -1000, -1000,
	-1000, -1000, 206, -1000, -1000, 442, -1000, 440, -1000, -1000,
	-1000, -1000, 174, 428, 445, 52, -1000, -1000, -1000, 194,
	-1000, -1000, -1000, -1000, -1000, 444, -1000, 426, 413, 395,
	390, 154, 256, 205, 236, 156, 254, 328, 164, 138,
	249, -26, 18, 18, -22, -22, -67, -67, -67, -67,
	-56, -56, -56, -56, -56, -56, 206, 174, 174, 174,
	248, -1000, 281, -1000, 197, -1000, 247, -1000, 275, 340,
	317, 435, 416, 414, 391, 386, 379, -1000, -1000, -1000,
	-1000, -1000, -1000, 51, 236, 113, 129, 163, 238, 146,
	151, 51, 279, 150, 241, 121, -1000, -1000, 120, -1000,
	367, 199, 206, 229, 442, 363, -1000, 439, 336, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	139, -1000, 124, 187, 29, 187, 280, -1, 174, -1,
	127, 73, 295, 108, 137, -1000, -1000, 130, -1000, 279,
	392, -1000, -1000, 235, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, 51, 29, 187, 29, -1000, -1000, 206, -1000, -1,
	-1000, 175, -1000, -1000, -1000, 37, 294, 290, 74, 51,
	109, -1000, 362, -1000, 29, -1000, 378, 30, 29, 23,
	-1, -1, 287, -1000, -1000, 223, 60, 29, -1000, -1000,
	-1, 344, -1000, -1000, 191, 330, 56, -1000,
}
var exprPgo = [...]int{

	0, 489, 16, 488, 2, 9, 433, 3, 15, 11,
	487, 486, 485, 484, 7, 483, 482, 481, 480, 479,
	478, 417, 477, 13, 5, 476, 475, 460, 6, 459,
	71, 458, 457, 4, 456, 455, 8, 454, 1, 453,
	0,
}
var exprR1 = [...]int{

	0, 1, 2, 2, 7, 7, 7, 7, 7, 7,
	6, 6, 6, 8, 8, 8, 8, 8, 8, 8,
	8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
	8, 8, 8, 8, 8, 8, 8, 8, 8, 38,
	38, 38, 13, 13, 13, 11, 11, 11, 11, 15,
	15, 15, 15, 15, 15, 20, 3, 3, 3, 3,
	14, 14, 14, 10, 10, 9, 9, 9, 9, 23,
	23, 24, 24, 24, 24, 24, 24, 17, 30, 30,
	29, 29, 22, 22, 22, 22, 35, 31, 33, 33,
	34, 34, 34, 32, 28, 28, 28, 28, 28, 28,
	28, 28, 36, 37, 37, 39, 39, 27, 27, 27,
	27, 27, 27, 27, 25, 25, 25, 25, 25, 25,
	25, 26, 26, 26, 26, 26, 26, 26, 18, 18,
	18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
	18, 18, 18, 21, 21, 19, 19, 19, 16, 16,
	16, 16, 16, 16, 16, 16, 16, 12, 12, 12,
	12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
	12, 40, 5, 5, 4, 4, 4, 4,
}
var exprR2 = [...]int{

	0, 1, 1, 1, 1, 1, 1, 1, 1, 3,
	1, 2, 3, 2, 3, 4, 5, 3, 4, 5,
	6, 3, 4, 5, 6, 3, 4, 5, 6, 4,
	5, 6, 7, 3, 4, 4, 5, 3, 2, 3,
	6, 3, 1, 1, 1, 4, 6, 5, 7, 4,
	5, 5, 6, 7, 7, 12, 1, 1, 1, 1,
	3, 3, 3, 1, 3, 3, 3, 3, 3, 1,
	2, 1, 2, 2, 2, 2, 2, 1, 2, 5,
	1, 2, 1, 1, 2, 1, 2, 2, 3, 3,
	1, 3, 3, 2, 1, 1, 1, 3, 2, 3,
	3, 3, 3, 1, 3, 1, 1, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 4, 4,
	4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
	4, 4, 4, 0, 1, 1, 2, 2, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 2, 1, 3, 4, 4, 3, 3,
}
var exprChk = [...]int{

	-1000, -1, -2, -6, -7, -14, 23, -11, -15, -18,
	-19, -20, 15, -12, -16, 7, 74, 75, 61, 27,
	28, 38, 39, 48, 49, 50, 51, 52, 53, 54,
	58, 59, 60, 29, 30, 33, 31, 32, 34, 35,
	36, 37, 65, 66, 67, 74, 75, 76, 77, 78,
	79, 68, 69, 72, 73, 70, 71, -23, -24, -29,
	44, -30, -3, 21, 22, 14, 69, -7, -6, -2,
	-10, 2, -9, 5, 23, 23, -4, 25, 26, 7,
	7, 23, -21, 40, -21, -21, -21, -21, -21, -21,
	-21, -21, -21, -21, -21, -21, -21, -21, -24, -30,
	-22, -35, -28, -31, -32, 41, 43, 42, 62, -9,
	-39, -26, 23, 45, 46, 5, -27, -25, 6, -17,
	64, 24, 24, 16, 2, 19, 16, 12, 69, 13,
	14, -8, 7, -14, 23, -7, 7, 23, 23, 23,
	-7, -2, -2, -2, -2, -2, -2, -2, -2, -2,
	-2, -2, -2, -2, -2, -2, -28, 66, 19, 65,
	-37, -36, 5, 6, -28, 6, -34, -33, 5, 12,
	69, 72, 73, 70, 71, 68, 23, -9, 6, 6,
	6, 6, 2, 24, 19, 9, -38, -23, 44, -14,
	-8, 24, 19, -7, 7, -5, 24, 5, -5, 24,
	19, -28, -28, -28, 19, 12, 24, 19, 12, 8,
	4, 7, 8, 4, 7, 8, 4, 7, 8, 4,
	7, 8, 4, 7, 8, 4, 7, 8, 4, 7,
	6, -4, -8, -40, -38, -23, 63, 9, 44, 9,
	-38, 47, 24, -38, -23, 24, -4, -7, 24, 19,
	19, 24, 24, 6, -36, 6, -33, 2, 5, 6,
	24, 24, -38, -23, -38, 8, -40, -28, -40, 9,
	5, -13, 55, 56, 57, 9, 24, 24, -38, 24,
	-7, 5, 19, -4, -38, -40, 23, -40, -38, 44,
	9, 9, 24, -4, 24, 6, 5, -38, -40, -40,
	9, 19, 24, -40, 6, 19, 6, 24,
}
var exprDef = [...]int{

	0, -2, 1, 2, 3, 10, 0, 4, 5, 6,
	7, 8, 0, 0, 0, 145, 0, 0, 0, 157,
	158, 159, 160, 161, 162, 163, 164, 165, 166, 167,
	168, 169, 170, 148, 149, 150, 151, 152, 153, 154,
	155, 156, 143, 143, 143, 143, 143, 143, 143, 143,
	143, 143, 143, 143, 143, 143, 143, 11, 69, 71,
	0, 80, 0, 56, 57, 58, 59, 3, 2, 0,
	0, 0, 63, 0, 0, 0, 0, 0, 0, 146,
	147, 0, 0, 144, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 70, 81,
	72, 73, 74, 75, 76, 82, 83, 0, 85, 94,
	95, 96, 0, 0, 0, 0, 105, 106, 78, 0,
	77, 9, 12, 60, 61, 0, 62, 0, 0, 0,
	0, 0, 0, 0, 0, 3, 145, 0, 0, 0,
	3, 128, 129, 130, 131, 132, 133, 134, 135, 136,
	137, 138, 139, 140, 141, 142, 98, 0, 0, 0,
	86, 103, 0, 84, 0, 87, 93, 90, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 64, 65, 66,
	67, 68, 38, 45, 0, 13, 0, 0, 0, 0,
	0, 49, 0, 3, 145, 0, 176, 172, 0, 177,
	0, 99, 100, 101, 0, 0, 97, 0, 0, 112,
	119, 126, 111, 118, 125, 107, 114, 121, 108, 115,
	122, 109, 116, 123, 110, 117, 124, 113, 120, 127,
	0, 47, 0, 14, 17, 33, 0, 21, 0, 25,
	0, 0, 0, 0, 0, 37, 51, 3, 50, 0,
	0, 174, 175, 0, 104, 102, 91, 92, 88, 89,
	79, 46, 18, 34, 35, 171, 22, 41, 26, 29,
	39, 0, 42, 43, 44, 15, 0, 0, 0, 52,
	3, 173, 0, 48, 36, 30, 0, 16, 19, 0,
	23, 27, 0, 53, 54, 0, 0, 20, 24, 28,
	31, 0, 40, 32, 0, 0, 0, 55,
}
var exprTok1 = [...]int{

	1,
}
var exprTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
	72, 73, 74, 75, 76, 77, 78, 79,
}
var exprTok3 = [...]int{
	0,
}

var exprErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}


/*	parser for yacc output	*/

var (
	exprDebug        = 0
	exprErrorVerbose = false
)

type exprLexer interface {
	Lex(lval *exprSymType) int
	Error(s string)
}

type exprParser interface {
	Parse(exprLexer) int
	Lookahead() int
}

type exprParserImpl struct {
	lval  exprSymType
	stack [exprInitialStackSize]exprSymType
	char  int
}

func (p *exprParserImpl) Lookahead() int {
	return p.char
}

func exprNewParser() exprParser {
	return &exprParserImpl{}
}

const exprFlag = -1000

func exprTokname(c int) string {
	if c >= 1 && c-1 < len(exprToknames) {
		if exprToknames[c-1] != "" {
			return exprToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func exprStatname(s int) string {
	if s >= 0 && s < len(exprStatenames) {
		if exprStatenames[s] != "" {
			return exprStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func exprErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !exprErrorVerbose {
		return "syntax error"
	}

	for _, e := range exprErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + exprTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := exprPact[state]
	for tok := TOKSTART; tok-1 < len(exprToknames); tok++ {
		if n := base + tok; n >= 0 && n < exprLast && exprChk[exprAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if exprDef[state] == -2 {
		i := 0
		for exprExca[i] != -1 || exprExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; exprExca[i] >= 0; i += 2 {
			tok := exprExca[i]
			if tok < TOKSTART || exprExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if exprExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += exprTokname(tok)
	}
	return res
}

func exprlex1(lex exprLexer, lval *exprSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = exprTok1[0]
		goto out
	}
	if char < len(exprTok1) {
		token = exprTok1[char]
		goto out
	}
	if char >= exprPrivate {
		if char < exprPrivate+len(exprTok2) {
			token = exprTok2[char-exprPrivate]
			goto out
		}
	}
	for i := 0; i < len(exprTok3); i += 2 {
		token = exprTok3[i+0]
		if token == char {
			token = exprTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = exprTok2[1] /* unknown char */
	}
	if exprDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", exprTokname(token), uint(char))
	}
	return char, token
}

func exprParse(exprlex exprLexer) int {
	return exprNewParser().Parse(exprlex)
}

func (exprrcvr *exprParserImpl) Parse(exprlex exprLexer) int {
	var exprn int
	var exprVAL exprSymType
	var exprDollar []exprSymType
	_ = exprDollar // silence set and not used
	exprS := exprrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	exprstate := 0
	exprrcvr.char = -1
	exprtoken := -1 // exprrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		exprstate = -1
		exprrcvr.char = -1
		exprtoken = -1
	}()
	exprp := -1
	goto exprstack

ret0:
	return 0

ret1:
	return 1

exprstack:
	/* put a state and value onto the stack */
	if exprDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", exprTokname(exprtoken), exprStatname(exprstate))
	}

	exprp++
	if exprp >= len(exprS) {
		nyys := make([]exprSymType, len(exprS)*2)
		copy(nyys, exprS)
		exprS = nyys
	}
	exprS[exprp] = exprVAL
	exprS[exprp].yys = exprstate

exprnewstate:
	exprn = exprPact[exprstate]
	if exprn <= exprFlag {
		goto exprdefault /* simple state */
	}
	if exprrcvr.char < 0 {
		exprrcvr.char, exprtoken = exprlex1(exprlex, &exprrcvr.lval)
	}
	exprn += exprtoken
	if exprn < 0 || exprn >= exprLast {
		goto exprdefault
	}
	exprn = exprAct[exprn]
	if exprChk[exprn] == exprtoken { /* valid shift */
		exprrcvr.char = -1
		exprtoken = -1
		exprVAL = exprrcvr.lval
		exprstate = exprn
		if Errflag > 0 {
			Errflag--
		}
		goto exprstack
	}

exprdefault:
	/* default state action */
	exprn = exprDef[exprstate]
	if exprn == -2 {
		if exprrcvr.char < 0 {
			exprrcvr.char, exprtoken = exprlex1(exprlex, &exprrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if exprExca[xi+0] == -1 && exprExca[xi+1] == exprstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			exprn = exprExca[xi+0]
			if exprn < 0 || exprn == exprtoken {
				break
			}
		}
		exprn = exprExca[xi+1]
		if exprn < 0 {
			goto ret0
		}
	}
	if exprn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			exprlex.Error(exprErrorMessage(exprstate, exprtoken))
			Nerrs++
			if exprDebug >= 1 {
				__yyfmt__.Printf("%s", exprStatname(exprstate))
				__yyfmt__.Printf(" saw %s\n", exprTokname(exprtoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for exprp >= 0 {
				exprn = exprPact[exprS[exprp].yys] + exprErrCode
				if exprn >= 0 && exprn < exprLast {
					exprstate = exprAct[exprn] /* simulate a shift of "error" */
					if exprChk[exprstate] == exprErrCode {
						goto exprstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if exprDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", exprS[exprp].yys)
				}
				exprp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if exprDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", exprTokname(exprtoken))
			}
			if exprtoken == exprEofCode {
				goto ret1
			}
			exprrcvr.char = -1
			exprtoken = -1
			goto exprnewstate /* try again in the same state */
		}
	}

	/* reduction by production exprn */
	if exprDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", exprn, exprStatname(exprstate))
	}

	exprnt := exprn
	exprpt := exprp
	_ = exprpt // guard against "declared and not used"

	exprp -= exprR2[exprn]
	// exprp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if exprp+1 >= len(exprS) {
		nyys := make([]exprSymType, len(exprS)*2)
		copy(nyys, exprS)
		exprS = nyys
	}
	exprVAL = exprS[exprp+1]

	/* consult goto table to find next state */
	exprn = exprR1[exprn]
	exprg := exprPgo[exprn]
	exprj := exprg + exprS[exprp].yys + 1

	if exprj >= exprLast {
		exprstate = exprAct[exprg]
	} else {
		exprstate = exprAct[exprj]
		if exprChk[exprstate] != -exprn {
			exprstate = exprAct[exprg]
		}
	}
	// dummy call; replaced with literal code
	switch exprnt {

	case 1:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprlex.(*parser).expr = exprDollar[1].Expr
		}
	case 2:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.Expr = exprDollar[1].LogExpr
		}
	case 3:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.Expr = exprDollar[1].MetricExpr
		}
	case 4:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricExpr = exprDollar[1].RangeAggregationExpr
		}
	case 5:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricExpr = exprDollar[1].VectorAggregationExpr
		}
	case 6:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricExpr = exprDollar[1].BinOpExpr
		}
	case 7:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricExpr = exprDollar[1].LiteralExpr
		}
	case 8:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricExpr = exprDollar[1].LabelReplaceExpr
		}
	case 9:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.MetricExpr = exprDollar[2].MetricExpr
		}
	case 10:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.LogExpr = newMatcherExpr(exprDollar[1].Selector)
		}
	case 11:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.LogExpr = newPipelineExpr(newMatcherExpr(exprDollar[1].Selector), exprDollar[2].PipelineExpr)
		}
	case 12:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LogExpr = exprDollar[2].LogExpr
		}
	case 13:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.LogRangeExpr = newLogRange(newMatcherExpr(exprDollar[1].Selector), exprDollar[2].duration, nil, nil)
		}
	case 14:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LogRangeExpr = newLogRange(newMatcherExpr(exprDollar[1].Selector), exprDollar[2].duration, nil, exprDollar[3].OffsetExpr)
		}
	case 15:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.LogRangeExpr = newLogRange(newMatcherExpr(exprDollar[2].Selector), exprDollar[4].duration, nil, nil)
		}
	case 16:
		exprDollar = exprS[exprpt-5 : exprpt+1]
		{
			exprVAL.LogRangeExpr = newLogRange(newMatcherExpr(exprDollar[2].Selector), exprDollar[4].duration, nil, exprDollar[5].OffsetExpr)
		}
	case 17:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LogRangeExpr = newLogRange(newMatcherExpr(exprDollar[1].Selector), exprDollar[2].duration, exprDollar[3].UnwrapExpr, nil)
		}
	case 18:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.LogRangeExpr = newLogRange(newMatcherExpr(exprDollar[1].Selector), exprDollar[2].duration, exprDollar[4].UnwrapExpr, exprDollar[3].OffsetExpr)
		}
	case 19:
		exprDollar = exprS[exprpt-5 : exprpt+1]
		{
			exprVAL.LogRangeExpr = newLogRange(newMatcherExpr(exprDollar[2].Selector), exprDollar[4].duration, exprDollar[5].UnwrapExpr, nil)
		}
	case 20:
		exprDollar = exprS[exprpt-6 : exprpt+1]
		{
			exprVAL.LogRangeExpr = newLogRange(newMatcherExpr(exprDollar[2].Selector), exprDollar[4].duration, exprDollar[6].UnwrapExpr, exprDollar[5].OffsetExpr)
		}
	case 21:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LogRangeExpr = newLogRange(newMatcherExpr(exprDollar[1].Selector), exprDollar[3].duration, exprDollar[2].UnwrapExpr, nil)
		}
	case 22:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.LogRangeExpr = newLogRange(newMatcherExpr(exprDollar[1].Selector), exprDollar[3].duration, exprDollar[2].UnwrapExpr, exprDollar[4].OffsetExpr)
		}
	case 23:
		exprDollar = exprS[exprpt-5 : exprpt+1]
		{
			exprVAL.LogRangeExpr = newLogRange(newMatcherExpr(exprDollar[2].Selector), exprDollar[5].duration, exprDollar[3].UnwrapExpr, nil)
		}
	case 24:
		exprDollar = exprS[exprpt-6 : exprpt+1]
		{
			exprVAL.LogRangeExpr = newLogRange(newMatcherExpr(exprDollar[2].Selector), exprDollar[5].duration, exprDollar[3].UnwrapExpr, exprDollar[6].OffsetExpr)
		}
	case 25:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LogRangeExpr = newLogRange(newPipelineExpr(newMatcherExpr(exprDollar[1].Selector), exprDollar[2].PipelineExpr), exprDollar[3].duration, nil, nil)
		}
	case 26:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.LogRangeExpr = newLogRange(newPipelineExpr(newMatcherExpr(exprDollar[1].Selector), exprDollar[2].PipelineExpr), exprDollar[3].duration, nil, exprDollar[4].OffsetExpr)
		}
	case 27:
		exprDollar = exprS[exprpt-5 : exprpt+1]
		{
			exprVAL.LogRangeExpr = newLogRange(newPipelineExpr(newMatcherExpr(exprDollar[2].Selector), exprDollar[3].PipelineExpr), exprDollar[5].duration, nil, nil)
		}
	case 28:
		exprDollar = exprS[exprpt-6 : exprpt+1]
		{
			exprVAL.LogRangeExpr = newLogRange(newPipelineExpr(newMatcherExpr(exprDollar[2].Selector), exprDollar[3].PipelineExpr), exprDollar[5].duration, nil, exprDollar[6].OffsetExpr)
		}
	case 29:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.LogRangeExpr = newLogRange(newPipelineExpr(newMatcherExpr(exprDollar[1].Selector), exprDollar[2].PipelineExpr), exprDollar[4].duration, exprDollar[3].UnwrapExpr, nil)
		}
	case 30:
		exprDollar = exprS[exprpt-5 : exprpt+1]
		{
			exprVAL.LogRangeExpr = newLogRange(newPipelineExpr(newMatcherExpr(exprDollar[1].Selector), exprDollar[2].PipelineExpr), exprDollar[4].duration, exprDollar[3].UnwrapExpr, exprDollar[5].OffsetExpr)
		}
	case 31:
		exprDollar = exprS[exprpt-6 : exprpt+1]
		{
			exprVAL.LogRangeExpr = newLogRange(newPipelineExpr(newMatcherExpr(exprDollar[2].Selector), exprDollar[3].PipelineExpr), exprDollar[6].duration, exprDollar[4].UnwrapExpr, nil)
		}
	case 32:
		exprDollar = exprS[exprpt-7 : exprpt+1]
		{
			exprVAL.LogRangeExpr = newLogRange(newPipelineExpr(newMatcherExpr(exprDollar[2].Selector), exprDollar[3].PipelineExpr), exprDollar[6].duration, exprDollar[4].UnwrapExpr, exprDollar[7].OffsetExpr)
		}
	case 33:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LogRangeExpr = newLogRange(newPipelineExpr(newMatcherExpr(exprDollar[1].Selector), exprDollar[3].PipelineExpr), exprDollar[2].duration, nil, nil)
		}
	case 34:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.LogRangeExpr = newLogRange(newPipelineExpr(newMatcherExpr(exprDollar[1].Selector), exprDollar[4].PipelineExpr), exprDollar[2].duration, nil, exprDollar[3].OffsetExpr)
		}
	case 35:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.LogRangeExpr = newLogRange(newPipelineExpr(newMatcherExpr(exprDollar[1].Selector), exprDollar[3].PipelineExpr), exprDollar[2].duration, exprDollar[4].UnwrapExpr, nil)
		}
	case 36:
		exprDollar = exprS[exprpt-5 : exprpt+1]
		{
			exprVAL.LogRangeExpr = newLogRange(newPipelineExpr(newMatcherExpr(exprDollar[1].Selector), exprDollar[4].PipelineExpr), exprDollar[2].duration, exprDollar[5].UnwrapExpr, exprDollar[3].OffsetExpr)
		}
	case 37:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LogRangeExpr = exprDollar[2].LogRangeExpr
		}
	case 39:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.UnwrapExpr = newUnwrapExpr(exprDollar[3].str, "")
		}
	case 40:
		exprDollar = exprS[exprpt-6 : exprpt+1]
		{
			exprVAL.UnwrapExpr = newUnwrapExpr(exprDollar[5].str, exprDollar[3].ConvOp)
		}
	case 41:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.UnwrapExpr = exprDollar[1].UnwrapExpr.addPostFilter(exprDollar[3].LabelFilter)
		}
	case 42:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.ConvOp = OpConvBytes
		}
	case 43:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.ConvOp = OpConvDuration
		}
	case 44:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.ConvOp = OpConvDurationSeconds
		}
	case 45:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.RangeAggregationExpr = newRangeAggregationExpr(exprDollar[3].LogRangeExpr, exprDollar[1].RangeOp, nil, nil)
		}
	case 46:
		exprDollar = exprS[exprpt-6 : exprpt+1]
		{
			exprVAL.RangeAggregationExpr = newRangeAggregationExpr(exprDollar[5].LogRangeExpr, exprDollar[1].RangeOp, nil, &exprDollar[3].str)
		}
	case 47:
		exprDollar = exprS[exprpt-5 : exprpt+1]
		{
			exprVAL.RangeAggregationExpr = newRangeAggregationExpr(exprDollar[3].LogRangeExpr, exprDollar[1].RangeOp, exprDollar[5].Grouping, nil)
		}
	case 48:
		exprDollar = exprS[exprpt-7 : exprpt+1]
		{
			exprVAL.RangeAggregationExpr = newRangeAggregationExpr(exprDollar[5].LogRangeExpr, exprDollar[1].RangeOp, exprDollar[7].Grouping, &exprDollar[3].str)
		}
	case 49:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.VectorAggregationExpr = mustNewVectorAggregationExpr(exprDollar[3].MetricExpr, exprDollar[1].VectorOp, nil, nil)
		}
	case 50:
		exprDollar = exprS[exprpt-5 : exprpt+1]
		{
			exprVAL.VectorAggregationExpr = mustNewVectorAggregationExpr(exprDollar[4].MetricExpr, exprDollar[1].VectorOp, exprDollar[2].Grouping, nil)
		}
	case 51:
		exprDollar = exprS[exprpt-5 : exprpt+1]
		{
			exprVAL.VectorAggregationExpr = mustNewVectorAggregationExpr(exprDollar[3].MetricExpr, exprDollar[1].VectorOp, exprDollar[5].Grouping, nil)
		}
	case 52:
		exprDollar = exprS[exprpt-6 : exprpt+1]
		{
			exprVAL.VectorAggregationExpr = mustNewVectorAggregationExpr(exprDollar[5].MetricExpr, exprDollar[1].VectorOp, nil, &exprDollar[3].str)
		}
	case 53:
		exprDollar = exprS[exprpt-7 : exprpt+1]
		{
			exprVAL.VectorAggregationExpr = mustNewVectorAggregationExpr(exprDollar[5].MetricExpr, exprDollar[1].VectorOp, exprDollar[7].Grouping, &exprDollar[3].str)
		}
	case 54:
		exprDollar = exprS[exprpt-7 : exprpt+1]
		{
			exprVAL.VectorAggregationExpr = mustNewVectorAggregationExpr(exprDollar[6].MetricExpr, exprDollar[1].VectorOp, exprDollar[2].Grouping, &exprDollar[4].str)
		}
	case 55:
		exprDollar = exprS[exprpt-12 : exprpt+1]
		{
			exprVAL.LabelReplaceExpr = mustNewLabelReplaceExpr(exprDollar[3].MetricExpr, exprDollar[5].str, exprDollar[7].str, exprDollar[9].str, exprDollar[11].str)
		}
	case 56:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.Filter = labels.MatchRegexp
		}
	case 57:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.Filter = labels.MatchEqual
		}
	case 58:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.Filter = labels.MatchNotRegexp
		}
	case 59:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.Filter = labels.MatchNotEqual
		}
	case 60:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.Selector = exprDollar[2].Matchers
		}
	case 61:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.Selector = exprDollar[2].Matchers
		}
	case 62:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
		}
	case 63:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.Matchers = []*labels.Matcher{exprDollar[1].Matcher}
		}
	case 64:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.Matchers = append(exprDollar[1].Matchers, exprDollar[3].Matcher)
		}
	case 65:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.Matcher = mustNewMatcher(labels.MatchEqual, exprDollar[1].str, exprDollar[3].str)
		}
	case 66:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.Matcher = mustNewMatcher(labels.MatchNotEqual, exprDollar[1].str, exprDollar[3].str)
		}
	case 67:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.Matcher = mustNewMatcher(labels.MatchRegexp, exprDollar[1].str, exprDollar[3].str)
		}
	case 68:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.Matcher = mustNewMatcher(labels.MatchNotRegexp, exprDollar[1].str, exprDollar[3].str)
		}
	case 69:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.PipelineExpr = MultiStageExpr{exprDollar[1].PipelineStage}
		}
	case 70:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.PipelineExpr = append(exprDollar[1].PipelineExpr, exprDollar[2].PipelineStage)
		}
	case 71:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.PipelineStage = exprDollar[1].LineFilters
		}
	case 72:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.PipelineStage = exprDollar[2].LabelParser
		}
	case 73:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.PipelineStage = exprDollar[2].JSONExpressionParser
		}
	case 74:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.PipelineStage = &labelFilterExpr{LabelFilterer: exprDollar[2].LabelFilter}
		}
	case 75:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.PipelineStage = exprDollar[2].LineFormatExpr
		}
	case 76:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.PipelineStage = exprDollar[2].LabelFormatExpr
		}
	case 77:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.FilterOp = OpFilterIP
		}
	case 78:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.LineFilter = newLineFilterExpr(exprDollar[1].Filter, "", exprDollar[2].str)
		}
	case 79:
		exprDollar = exprS[exprpt-5 : exprpt+1]
		{
			exprVAL.LineFilter = newLineFilterExpr(exprDollar[1].Filter, exprDollar[2].FilterOp, exprDollar[4].str)
		}
	case 80:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.LineFilters = exprDollar[1].LineFilter
		}
	case 81:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.LineFilters = newNestedLineFilterExpr(exprDollar[1].LineFilters, exprDollar[2].LineFilter)
		}
	case 82:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.LabelParser = newLabelParserExpr(OpParserTypeJSON, "")
		}
	case 83:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.LabelParser = newLabelParserExpr(OpParserTypeLogfmt, "")
		}
	case 84:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.LabelParser = newLabelParserExpr(OpParserTypeRegexp, exprDollar[2].str)
		}
	case 85:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.LabelParser = newLabelParserExpr(OpParserTypeUnpack, "")
		}
	case 86:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.JSONExpressionParser = newJSONExpressionParser(exprDollar[2].JSONExpressionList)
		}
	case 87:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.LineFormatExpr = newLineFmtExpr(exprDollar[2].str)
		}
	case 88:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LabelFormat = log.NewRenameLabelFmt(exprDollar[1].str, exprDollar[3].str)
		}
	case 89:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LabelFormat = log.NewTemplateLabelFmt(exprDollar[1].str, exprDollar[3].str)
		}
	case 90:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.LabelsFormat = []log.LabelFmt{exprDollar[1].LabelFormat}
		}
	case 91:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LabelsFormat = append(exprDollar[1].LabelsFormat, exprDollar[3].LabelFormat)
		}
	case 93:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.LabelFormatExpr = newLabelFmtExpr(exprDollar[2].LabelsFormat)
		}
	case 94:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.LabelFilter = log.NewStringLabelFilter(exprDollar[1].Matcher)
		}
	case 95:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.LabelFilter = exprDollar[1].UnitFilter
		}
	case 96:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.LabelFilter = exprDollar[1].NumberFilter
		}
	case 97:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LabelFilter = exprDollar[2].LabelFilter
		}
	case 98:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.LabelFilter = log.NewAndLabelFilter(exprDollar[1].LabelFilter, exprDollar[2].LabelFilter)
		}
	case 99:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LabelFilter = log.NewAndLabelFilter(exprDollar[1].LabelFilter, exprDollar[3].LabelFilter)
		}
	case 100:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LabelFilter = log.NewAndLabelFilter(exprDollar[1].LabelFilter, exprDollar[3].LabelFilter)
		}
	case 101:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LabelFilter = log.NewOrLabelFilter(exprDollar[1].LabelFilter, exprDollar[3].LabelFilter)
		}
	case 102:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.JSONExpression = log.NewJSONExpr(exprDollar[1].str, exprDollar[3].str)
		}
	case 103:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.JSONExpressionList = []log.JSONExpression{exprDollar[1].JSONExpression}
		}
	case 104:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.JSONExpressionList = append(exprDollar[1].JSONExpressionList, exprDollar[3].JSONExpression)
		}
	case 105:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.UnitFilter = exprDollar[1].DurationFilter
		}
	case 106:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.UnitFilter = exprDollar[1].BytesFilter
		}
	case 107:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.DurationFilter = log.NewDurationLabelFilter(log.LabelFilterGreaterThan, exprDollar[1].str, exprDollar[3].duration)
		}
	case 108:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.DurationFilter = log.NewDurationLabelFilter(log.LabelFilterGreaterThanOrEqual, exprDollar[1].str, exprDollar[3].duration)
		}
	case 109:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.DurationFilter = log.NewDurationLabelFilter(log.LabelFilterLesserThan, exprDollar[1].str, exprDollar[3].duration)
		}
	case 110:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.DurationFilter = log.NewDurationLabelFilter(log.LabelFilterLesserThanOrEqual, exprDollar[1].str, exprDollar[3].duration)
		}
	case 111:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.DurationFilter = log.NewDurationLabelFilter(log.LabelFilterNotEqual, exprDollar[1].str, exprDollar[3].duration)
		}
	case 112:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.DurationFilter = log.NewDurationLabelFilter(log.LabelFilterEqual, exprDollar[1].str, exprDollar[3].duration)
		}
	case 113:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.DurationFilter = log.NewDurationLabelFilter(log.LabelFilterEqual, exprDollar[1].str, exprDollar[3].duration)
		}
	case 114:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.BytesFilter = log.NewBytesLabelFilter(log.LabelFilterGreaterThan, exprDollar[1].str, exprDollar[3].bytes)
		}
	case 115:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.BytesFilter = log.NewBytesLabelFilter(log.LabelFilterGreaterThanOrEqual, exprDollar[1].str, exprDollar[3].bytes)
		}
	case 116:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.BytesFilter = log.NewBytesLabelFilter(log.LabelFilterLesserThan, exprDollar[1].str, exprDollar[3].bytes)
		}
	case 117:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.BytesFilter = log.NewBytesLabelFilter(log.LabelFilterLesserThanOrEqual, exprDollar[1].str, exprDollar[3].bytes)
		}
	case 118:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.BytesFilter = log.NewBytesLabelFilter(log.LabelFilterNotEqual, exprDollar[1].str, exprDollar[3].bytes)
		}
	case 119:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.BytesFilter = log.NewBytesLabelFilter(log.LabelFilterEqual, exprDollar[1].str, exprDollar[3].bytes)
		}
	case 120:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.BytesFilter = log.NewBytesLabelFilter(log.LabelFilterEqual, exprDollar[1].str, exprDollar[3].bytes)
		}
	case 121:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.NumberFilter = log.NewNumericLabelFilter(log.LabelFilterGreaterThan, exprDollar[1].str, mustNewFloat(exprDollar[3].str))
		}
	case 122:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.NumberFilter = log.NewNumericLabelFilter(log.LabelFilterGreaterThanOrEqual, exprDollar[1].str, mustNewFloat(exprDollar[3].str))
		}
	case 123:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.NumberFilter = log.NewNumericLabelFilter(log.LabelFilterLesserThan, exprDollar[1].str, mustNewFloat(exprDollar[3].str))
		}
	case 124:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.NumberFilter = log.NewNumericLabelFilter(log.LabelFilterLesserThanOrEqual, exprDollar[1].str, mustNewFloat(exprDollar[3].str))
		}
	case 125:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.NumberFilter = log.NewNumericLabelFilter(log.LabelFilterNotEqual, exprDollar[1].str, mustNewFloat(exprDollar[3].str))
		}
	case 126:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.NumberFilter = log.NewNumericLabelFilter(log.LabelFilterEqual, exprDollar[1].str, mustNewFloat(exprDollar[3].str))
		}
	case 127:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.NumberFilter = log.NewNumericLabelFilter(log.LabelFilterEqual, exprDollar[1].str, mustNewFloat(exprDollar[3].str))
		}
	case 128:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.BinOpExpr = mustNewBinOpExpr("or", exprDollar[3].BinOpModifier, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 129:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.BinOpExpr = mustNewBinOpExpr("and", exprDollar[3].BinOpModifier, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 130:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.BinOpExpr = mustNewBinOpExpr("unless", exprDollar[3].BinOpModifier, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 131:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.BinOpExpr = mustNewBinOpExpr("+", exprDollar[3].BinOpModifier, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 132:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.BinOpExpr = mustNewBinOpExpr("-", exprDollar[3].BinOpModifier, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 133:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.BinOpExpr = mustNewBinOpExpr("*", exprDollar[3].BinOpModifier, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 134:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.BinOpExpr = mustNewBinOpExpr("/", exprDollar[3].BinOpModifier, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 135:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.BinOpExpr = mustNewBinOpExpr("%", exprDollar[3].BinOpModifier, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 136:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.BinOpExpr = mustNewBinOpExpr("^", exprDollar[3].BinOpModifier, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 137:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.BinOpExpr = mustNewBinOpExpr("==", exprDollar[3].BinOpModifier, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 138:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.BinOpExpr = mustNewBinOpExpr("!=", exprDollar[3].BinOpModifier, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 139:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.BinOpExpr = mustNewBinOpExpr(">", exprDollar[3].BinOpModifier, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 140:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.BinOpExpr = mustNewBinOpExpr(">=", exprDollar[3].BinOpModifier, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 141:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.BinOpExpr = mustNewBinOpExpr("<", exprDollar[3].BinOpModifier, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 142:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.BinOpExpr = mustNewBinOpExpr("<=", exprDollar[3].BinOpModifier, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 143:
		exprDollar = exprS[exprpt-0 : exprpt+1]
		{
			exprVAL.BinOpModifier = BinOpOptions{}
		}
	case 144:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.BinOpModifier = BinOpOptions{ReturnBool: true}
		}
	case 145:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.LiteralExpr = mustNewLiteralExpr(exprDollar[1].str, false)
		}
	case 146:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.LiteralExpr = mustNewLiteralExpr(exprDollar[2].str, false)
		}
	case 147:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.LiteralExpr = mustNewLiteralExpr(exprDollar[2].str, true)
		}
	case 148:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.VectorOp = OpTypeSum
		}
	case 149:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.VectorOp = OpTypeAvg
		}
	case 150:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.VectorOp = OpTypeCount
		}
	case 151:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.VectorOp = OpTypeMax
		}
	case 152:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.VectorOp = OpTypeMin
		}
	case 153:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.VectorOp = OpTypeStddev
		}
	case 154:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.VectorOp = OpTypeStdvar
		}
	case 155:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.VectorOp = OpTypeBottomK
		}
	case 156:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.VectorOp = OpTypeTopK
		}
	case 157:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.RangeOp = OpRangeTypeCount
		}
	case 158:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.RangeOp = OpRangeTypeRate
		}
	case 159:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.RangeOp = OpRangeTypeBytes
		}
	case 160:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.RangeOp = OpRangeTypeBytesRate
		}
	case 161:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.RangeOp = OpRangeTypeAvg
		}
	case 162:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.RangeOp = OpRangeTypeSum
		}
	case 163:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.RangeOp = OpRangeTypeMin
		}
	case 164:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.RangeOp = OpRangeTypeMax
		}
	case 165:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.RangeOp = OpRangeTypeStdvar
		}
	case 166:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.RangeOp = OpRangeTypeStddev
		}
	case 167:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.RangeOp = OpRangeTypeQuantile
		}
	case 168:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.RangeOp = OpRangeTypeFirst
		}
	case 169:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.RangeOp = OpRangeTypeLast
		}
	case 170:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.RangeOp = OpRangeTypeAbsent
		}
	case 171:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.OffsetExpr = newOffsetExpr(exprDollar[2].duration)
		}
	case 172:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.Labels = []string{exprDollar[1].str}
		}
	case 173:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.Labels = append(exprDollar[1].Labels, exprDollar[3].str)
		}
	case 174:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.Grouping = &grouping{without: false, groups: exprDollar[3].Labels}
		}
	case 175:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.Grouping = &grouping{without: true, groups: exprDollar[3].Labels}
		}
	case 176:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.Grouping = &grouping{without: false, groups: nil}
		}
	case 177:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.Grouping = &grouping{without: true, groups: nil}
		}
	}
	goto exprstack /* stack new state and value */
}
